package practica11;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class MainFrm extends javax.swing.JFrame {

    public MainFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaResultados = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnEntrada.setText("Entrada ");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        jButton3.setText("Mensajes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Opciones");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        textAreaResultados.setColumns(20);
        textAreaResultados.setRows(5);
        jScrollPane1.setViewportView(textAreaResultados);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cuadro de dialogo");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(btnEntrada)
                    .addComponent(btnConfirmar)
                    .addComponent(jButton4))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnConfirmar)
                        .addGap(89, 89, 89)
                        .addComponent(btnEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(95, 95, 95)
                        .addComponent(jButton4)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //variables locales
        ImageIcon icono = new ImageIcon("src/practica11/agenda.png");
        
        /*
        Cuadro de dialogo para mostrar algun mensaje 
        -Ventana sencilla se asocia a la ventana padre y un texto
        */
        JOptionPane.showMessageDialog(null, "Datos capturados: ");
        
        //-Determine en la ventana un tipo de icono
        JOptionPane.showMessageDialog(this, "Esta es una ventana de emergencia", "Emergencia",
                JOptionPane.WARNING_MESSAGE);
        
        //-Definir un icono personalizado en la ventana del mensaje
        JOptionPane.showMessageDialog(this, "Credito de vivienda aprobado.", 
                "Vivienda", JOptionPane.WARNING_MESSAGE, icono);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        //variables para el metodo
        int valor;
        
        /*
        Cuadro de dialogo de confirmacion que puede ser: 
        -Basica (indica el padre del cuadro de dialogo y un texto
        */
        valor = JOptionPane.showConfirmDialog(null, "¿Confirmas movimiento");
        
        //Como valores 1(si), 0(no), 2(cancelar)
        textAreaResultados.setText("Respuesta del usario: " + valor);
        
        
        /*
        -Con titulo y botones (DEFAULT_OPTION, YES_NO_OPTION),
        YES_NO_CANCEL_OPTION, OK_CANCEL_OPTION)
        */
        valor = JOptionPane.showConfirmDialog(this, "¿Borrar dato?", 
                "Eliminar informacion", JOptionPane.YES_OPTION);
        
        /*
        DEFAULT_OPTION: Boton acepta (0)
        YES_NO_OPTION: Botones 1(si), 0(no)
        YES_NO_CANCEL_OPTION: 1(si), 0(no), 2(cancelar)
        OK_CANCEL_OPTION: Boton acepta (0), 2(cancelar)
        */
        textAreaResultados.setText("Respuesta del usuario: " + valor);
        
        /*
        -Con titulo, botones y tipo de mensaje (ERROR_MESSAGE, INFORMATION_MESSAGE,
        WARNING_MESSAGE, QUETION_MESSAGE, PLAIN_MESSAGE)
        */
        valor = JOptionPane.showConfirmDialog(this, "Autoriza el movimiento",
                "confirmacion", JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.INFORMATION_MESSAGE);
        
        textAreaResultados.setText("Respuesta del usario: " + valor);
        
        /*
        -Con titulo, botones, tipo de mensaje y un icono personalizado
        nombre y ruta de la imagen
        */
        ImageIcon icono = new ImageIcon("src/practica11/agenda.png");
        
        valor = JOptionPane.showConfirmDialog(this, "Autoriza el movimiento",
                "Confirmacion", JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE, icono);
        
        textAreaResultados.setText("Respuesta del usuario: " + valor);
        
        
        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        //Variable locales
        String respuesta;
        int edad;
        
        /*
        Cuadro de dialogo de entrada (solo devuelve cadenas) puede ser:
        -Basica, especificando el texto
        */
        respuesta = JOptionPane.showInputDialog("Ingresar nombre: ");
        textAreaResultados.setText("Nombre: " + respuesta + "\n");
        
        //-Con referencia a la ventana padre y el texto
        respuesta = JOptionPane.showInputDialog(this, "Captura edad: ");
        edad = Integer.parseInt(respuesta);
        textAreaResultados.append("Edad: " + edad + "\n");
        
        //-Con texto y valor predeterminado
        respuesta = JOptionPane.showInputDialog("Captura Apellido 1: ", "Lopez");
        textAreaResultados.append("Apellido 1: " + respuesta + "\n");
        
        //-Con asociacion al padre, texto, valor predeterminado
        respuesta = JOptionPane.showInputDialog(this, "Captura Apellido 2:", 
                "Lopez");
        textAreaResultados.append("Apellido 2: " + respuesta + "\n");
        
        //-Con asociacion al padre, texto, titulo, tipo de mensaje
        respuesta = JOptionPane.showInputDialog(this, "Captura domicilio:",
                "Dato de contacto", JOptionPane.INFORMATION_MESSAGE);
        textAreaResultados.append("Domicilio: " + respuesta + "\n");
        
        //-Con asociacion al padre, con titulo, tipo de mensaje, icono, lista de opciones y opcion predeterminada
        String opciones[] = {"Elige", "Jalisco", "Sinaloa", "Michoacan", "Yucatan"};
        ImageIcon icono = new ImageIcon("src/practica11/agenda.png");
        respuesta = JOptionPane.showInputDialog(this, "Estado que colinda con Jalisco: ",
                "Pregunta", JOptionPane.PLAIN_MESSAGE, icono,
                opciones, "Elige").toString();
        
        textAreaResultados.append("Estado: " + respuesta + "\n");
        
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //variables locales
        String opciones[] = {"Alfa", "Beta", "Gamma", "Epsilon", "Etha", "Otra"};
        ImageIcon icono = new ImageIcon("src/practica11/agenda.png");
        int respuesta;
        /*
        Este cuadro de dialogo personaliza las opciones a elegir por el usuario 
        se le asocia a una ventana, a un arreglo de cadenas y se puede personalizar
        un icono. Retorna un valor numerico
        */
        respuesta = JOptionPane.showOptionDialog(this, "Elige una de las letras: ",
                "Letras griegas", JOptionPane.DEFAULT_OPTION
                , JOptionPane.PLAIN_MESSAGE, icono, opciones,
                opciones[0]);
        textAreaResultados.append("Opcion Seleccionada: " + respuesta + "\n");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaResultados;
    // End of variables declaration//GEN-END:variables
}
