package practica14;

public class FrmMenu extends javax.swing.JFrame {
    
    private String usuario;
    private PilaAlumno alumnos;
    private PilaLibro libros;
    private PilaPrestamo prestamos;
    
    public FrmMenu(String usuario) {
        initComponents();
        setUsuario(usuario);
        iniciarPilas();
    }
    
    private void setUsuario(String usuario){
        this.usuario = usuario;
        labelUsuario.setText("Menu - Bienvenido " + this.usuario);
    }
    
    private void iniciarPilas(){
        alumnos = new PilaAlumno();
        libros = new PilaLibro();
        prestamos = new PilaPrestamo();
    }
    
    public void setAlumnos(PilaAlumno alumnos) {
        this.alumnos = alumnos;
    }

    public void setLibros(PilaLibro libros) {
        this.libros = libros;
    }

    public void setPrestamos(PilaPrestamo prestamos) {
        this.prestamos = prestamos;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumno = new javax.swing.JMenu();
        menuItemAlumnoRegistrar = new javax.swing.JMenuItem();
        menuItemAlumnoInformacion = new javax.swing.JMenuItem();
        menuLibro = new javax.swing.JMenu();
        menuItemLibroRegistrar = new javax.swing.JMenuItem();
        menuItemLibroInformacion = new javax.swing.JMenuItem();
        menuPrestamo = new javax.swing.JMenu();
        menuItemPrestamoRegistrar = new javax.swing.JMenuItem();
        menuItemPrestamoInformacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("Menu");

        menuAlumno.setText("Alumno");

        menuItemAlumnoRegistrar.setText("Registrar");
        menuItemAlumnoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnoRegistrarActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemAlumnoRegistrar);

        menuItemAlumnoInformacion.setText("Informacion");
        menuItemAlumnoInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnoInformacionActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemAlumnoInformacion);

        jMenuBar1.add(menuAlumno);

        menuLibro.setText("Libro");

        menuItemLibroRegistrar.setText("Registrar");
        menuItemLibroRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLibroRegistrarActionPerformed(evt);
            }
        });
        menuLibro.add(menuItemLibroRegistrar);

        menuItemLibroInformacion.setText("Informacion");
        menuItemLibroInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLibroInformacionActionPerformed(evt);
            }
        });
        menuLibro.add(menuItemLibroInformacion);

        jMenuBar1.add(menuLibro);

        menuPrestamo.setText("Prestamo");

        menuItemPrestamoRegistrar.setText("Registrar");
        menuItemPrestamoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrestamoRegistrarActionPerformed(evt);
            }
        });
        menuPrestamo.add(menuItemPrestamoRegistrar);

        menuItemPrestamoInformacion.setText("Informacion");
        menuItemPrestamoInformacion.setToolTipText("");
        menuItemPrestamoInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPrestamoInformacionActionPerformed(evt);
            }
        });
        menuPrestamo.add(menuItemPrestamoInformacion);

        jMenuBar1.add(menuPrestamo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 838, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelUsuario)
                .addContainerGap(434, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAlumnoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnoRegistrarActionPerformed
        // TODO add your handling code here:
        FrmRegistrarAlumno registroAlumnos = new FrmRegistrarAlumno(alumnos, this);
        registroAlumnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAlumnoRegistrarActionPerformed

    private void menuItemAlumnoInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnoInformacionActionPerformed
        // TODO add your handling code here:
        FrmInformacion infoAlumnos = new FrmInformacion(alumnos, this);
        infoAlumnos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAlumnoInformacionActionPerformed

    private void menuItemLibroRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLibroRegistrarActionPerformed
        // TODO add your handling code here:
        FrmRegistrarLibro registroLibro = new FrmRegistrarLibro(libros, this);
        registroLibro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemLibroRegistrarActionPerformed

    private void menuItemLibroInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLibroInformacionActionPerformed
        // TODO add your handling code here:
       FrmInformacion infoAlumnos = new FrmInformacion(libros, this);
       infoAlumnos.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_menuItemLibroInformacionActionPerformed

    private void menuItemPrestamoInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrestamoInformacionActionPerformed
        // TODO add your handling code here:
       FrmInformacion infoAlumnos = new FrmInformacion(prestamos, this);
       infoAlumnos.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_menuItemPrestamoInformacionActionPerformed

    private void menuItemPrestamoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPrestamoRegistrarActionPerformed
        // TODO add your handling code here:
        FrmRegistrarPrestamo registrarPrestamos = new FrmRegistrarPrestamo(prestamos, this);
        registrarPrestamos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemPrestamoRegistrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuItem menuItemAlumnoInformacion;
    private javax.swing.JMenuItem menuItemAlumnoRegistrar;
    private javax.swing.JMenuItem menuItemLibroInformacion;
    private javax.swing.JMenuItem menuItemLibroRegistrar;
    private javax.swing.JMenuItem menuItemPrestamoInformacion;
    private javax.swing.JMenuItem menuItemPrestamoRegistrar;
    private javax.swing.JMenu menuLibro;
    private javax.swing.JMenu menuPrestamo;
    // End of variables declaration//GEN-END:variables
}
