package practica06;

public class Registro extends javax.swing.JFrame {

    private String usuario;
    SmartTv smartv;
    public Registro() {
        initComponents();
        limpiar();
    }
    
    public void setUsuario(String usuario){
        this.usuario = usuario;
        labelUsuario.setText("Bienvenido de nuevo " + usuario);
    }
    
    private void limpiar(){
        textFieldMarca.setText("");
        textFieldModelo.setText("");
        textFieldPrecio.setText("");
        textFieldResolucion.setText("");
        textFieldTamanoPantalla.setText("");
        checkAndroidTv.setSelected(false);
        checkRoku.setSelected(false);
        checkSaphi.setSelected(false);
        checkTizen.setSelected(false);
        checkWebOS.setSelected(false);
        labelMensaje.setText("");
        
        textFieldMarca.requestFocus();
    }
    
    private boolean estaVacio(){
      return textFieldMarca.getText().isEmpty() && textFieldModelo.getText().isEmpty() &&
                textFieldPrecio.getText().isEmpty() && textFieldResolucion.getText().isEmpty() 
                && !(checkAndroidTv.isSelected() | checkRoku.isSelected() | checkSaphi.isSelected()
                | checkWebOS.isSelected()) && textFieldTamanoPantalla.getText().isEmpty();
    }
    
    private void controlCheckBox(java.awt.event.ActionEvent evt){
        checkAndroidTv.setSelected(false);
        checkRoku.setSelected(false);
        checkSaphi.setSelected(false);
        checkTizen.setSelected(false);
        checkWebOS.setSelected(false);
        
        if(evt.getSource().equals(checkAndroidTv)) checkAndroidTv.setSelected(true);
        else if(evt.getSource().equals(checkRoku)) checkRoku.setSelected(true);
        else if(evt.getSource().equals(checkSaphi)) checkSaphi.setSelected(true);
        else if(evt.getSource().equals(checkTizen)) checkTizen.setSelected(true);
        else if(evt.getSource().equals(checkWebOS)) checkWebOS.setSelected(true);
    }
    
    private String obtenerValorCheckBox(){
        if(checkAndroidTv.isSelected()) return checkAndroidTv.getText();
        if(checkRoku.isSelected()) return checkRoku.getText();
        if(checkSaphi.isSelected()) return checkSaphi.getText();
        if(checkTizen.isSelected()) return checkTizen.getText();
        if(checkWebOS.isSelected()) return checkWebOS.getText();
        return "no seleccionado";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textFieldMarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldTamanoPantalla = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textFieldPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textFieldResolucion = new javax.swing.JTextField();
        labelMensaje = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVerInfo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        scrollTextFieldModelo = new javax.swing.JScrollPane();
        textFieldModelo = new javax.swing.JTextArea();
        checkAndroidTv = new javax.swing.JCheckBox();
        checkRoku = new javax.swing.JCheckBox();
        checkWebOS = new javax.swing.JCheckBox();
        checkSaphi = new javax.swing.JCheckBox();
        checkTizen = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelUsuario.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de SmartTv");

        jLabel1.setText("Marca:");

        textFieldMarca.setText("jTextField1");
        textFieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldMarcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldMarcaKeyTyped(evt);
            }
        });

        jLabel3.setText("Modelo y especificaciones:");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jLabel4.setText("Tamaño de la pantalla:");

        textFieldTamanoPantalla.setText("jTextField3");
        textFieldTamanoPantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldTamanoPantallaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldTamanoPantallaKeyTyped(evt);
            }
        });

        jLabel5.setText("Precio:");

        textFieldPrecio.setText("jTextField4");
        textFieldPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldPrecioKeyTyped(evt);
            }
        });

        jLabel6.setText("Sistema operativo:");

        jLabel7.setText("Resolucion:");

        textFieldResolucion.setText("jTextField6");

        labelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensaje.setText("jLabel8");

        btnAgregar.setText("agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnVerInfo.setText("ver informacion");
        btnVerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInfoActionPerformed(evt);
            }
        });

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textFieldModelo.setColumns(20);
        textFieldModelo.setRows(5);
        scrollTextFieldModelo.setViewportView(textFieldModelo);

        checkAndroidTv.setText("AndroidTv");
        checkAndroidTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAndroidTvActionPerformed(evt);
            }
        });

        checkRoku.setText("Roku");
        checkRoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRokuActionPerformed(evt);
            }
        });

        checkWebOS.setText("WebOS");
        checkWebOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWebOSActionPerformed(evt);
            }
        });

        checkSaphi.setText("Saphi");
        checkSaphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSaphiActionPerformed(evt);
            }
        });

        checkTizen.setText("Tizen");
        checkTizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTizenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(42, 42, 42)
                                .addComponent(checkAndroidTv, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkRoku, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkWebOS, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkSaphi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkTizen, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldMarca)
                                    .addComponent(textFieldTamanoPantalla)
                                    .addComponent(textFieldPrecio)
                                    .addComponent(textFieldResolucion)
                                    .addComponent(scrollTextFieldModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))))
                        .addGap(0, 164, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnAgregar)
                .addGap(41, 41, 41)
                .addComponent(btnLimpiar)
                .addGap(91, 91, 91)
                .addComponent(btnVerInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollTextFieldModelo)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldTamanoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkAndroidTv)
                    .addComponent(checkRoku)
                    .addComponent(checkWebOS)
                    .addComponent(checkSaphi)
                    .addComponent(checkTizen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(labelMensaje)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnVerInfo)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
        smartv = null;
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(!estaVacio()){
            String marca = textFieldMarca.getText();
            String modelo = textFieldModelo.getText();
            float precio = Float.parseFloat(textFieldPrecio.getText());
            String resolucion = textFieldResolucion.getText();
            int tamanoPantalla = Integer.parseInt(textFieldTamanoPantalla.getText());
            String sistemaOperativo = obtenerValorCheckBox();
            
            smartv = new SmartTv(sistemaOperativo, resolucion, marca, modelo, tamanoPantalla, precio);
            
            limpiar();
        }else labelMensaje.setText("Ingrese todos los datos que se piden");
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textFieldTamanoPantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldTamanoPantallaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isAlphabetic(caracter)) evt.consume();
    }//GEN-LAST:event_textFieldTamanoPantallaKeyTyped

    private void textFieldPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPrecioKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isAlphabetic(caracter)) evt.consume();
    }//GEN-LAST:event_textFieldPrecioKeyTyped

    private void textFieldMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldMarcaKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == 10) textFieldModelo.requestFocus();
    }//GEN-LAST:event_textFieldMarcaKeyPressed

    private void textFieldTamanoPantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldTamanoPantallaKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if(key == 10) textFieldPrecio.requestFocus();
    }//GEN-LAST:event_textFieldTamanoPantallaKeyPressed

    private void textFieldPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldPrecioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrecioKeyPressed

    private void btnVerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInfoActionPerformed
        // TODO add your handling code here:
        if(smartv != null){
            MostrarInfo infoVentana = new MostrarInfo();
            infoVentana.setData(smartv);
            infoVentana.setVisible(true);
        }else labelMensaje.setText("No hay informacion para mostrar");
    }//GEN-LAST:event_btnVerInfoActionPerformed

    private void checkAndroidTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAndroidTvActionPerformed
        // TODO add your handling code here:
        controlCheckBox(evt);
    }//GEN-LAST:event_checkAndroidTvActionPerformed

    private void checkRokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRokuActionPerformed
        // TODO add your handling code here:
        controlCheckBox(evt);
    }//GEN-LAST:event_checkRokuActionPerformed

    private void checkWebOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWebOSActionPerformed
        // TODO add your handling code here:
        controlCheckBox(evt);
    }//GEN-LAST:event_checkWebOSActionPerformed

    private void checkSaphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSaphiActionPerformed
        // TODO add your handling code here:
        controlCheckBox(evt);
    }//GEN-LAST:event_checkSaphiActionPerformed

    private void checkTizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTizenActionPerformed
        // TODO add your handling code here:
        controlCheckBox(evt);
    }//GEN-LAST:event_checkTizenActionPerformed

    private void textFieldMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldMarcaKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isDigit(caracter)) evt.consume();
    }//GEN-LAST:event_textFieldMarcaKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerInfo;
    private javax.swing.JCheckBox checkAndroidTv;
    private javax.swing.JCheckBox checkRoku;
    private javax.swing.JCheckBox checkSaphi;
    private javax.swing.JCheckBox checkTizen;
    private javax.swing.JCheckBox checkWebOS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JScrollPane scrollTextFieldModelo;
    private javax.swing.JTextField textFieldMarca;
    private javax.swing.JTextArea textFieldModelo;
    private javax.swing.JTextField textFieldPrecio;
    private javax.swing.JTextField textFieldResolucion;
    private javax.swing.JTextField textFieldTamanoPantalla;
    // End of variables declaration//GEN-END:variables
}
