package practica05;

public class main extends javax.swing.JFrame {

    Deporte[] deportes = new Deporte[20];
    int contDeporte = 0;
    
    public main() {
        initComponents();
        limpiarCampos();
    }
    
    private void limpiarCampos(){
        tFieldGanarPuntos.setText("");
        tFieldNombre.setText("");
        tFieldNumJugadores.setText("");
        tFieldPopularidad.setText("");
        
        labelMensaje.setText("");
    }
    
    private boolean textFieldVacios(){
        return (tFieldGanarPuntos.getText().isEmpty() && tFieldNombre.getText().isEmpty() &&
                tFieldPopularidad.getText().isEmpty()&& tFieldNumJugadores.getText().isEmpty());
    }
    
    private void agregar(){
        if(contDeporte==20) labelMensaje.setText("El arreglo de deportes esta lleno");
        else if(!textFieldVacios()){
            String nombre;
            int numJugadores;
            float popularidad;
            String accionPuntaje;
            
            nombre = tFieldNombre.getText();
            numJugadores = Integer.parseInt(tFieldNumJugadores.getText());
            popularidad = Float.parseFloat(tFieldPopularidad.getText());
            accionPuntaje = tFieldGanarPuntos.getText();
            
            deportes[contDeporte] = new Deporte(nombre, numJugadores, popularidad, accionPuntaje);
            
            contDeporte++;
            
            limpiarCampos();
        }else labelMensaje.setText("No se han llenado todos los campos");
    }
    
    private int buscar(){
        if(contDeporte == 0) labelMensaje.setText("No hay deportes agregados");
        else if(!tFieldNombre.getText().isEmpty()){
            String nombre = tFieldNombre.getText();
            
            for(int i =0; i<contDeporte; i++){
                if(deportes[i].getNombre().equals(nombre)){
                    tFieldNumJugadores.setText(String.valueOf(deportes[i].getNumJugadores()));
                    tFieldPopularidad.setText(String.valueOf(deportes[i].getPopularidad()));
                    tFieldGanarPuntos.setText(deportes[i].getAccionPuntaje());
                    
                    labelMensaje.setText("La busqueda a sido exitosa");
                    
                    return i;
                }
            }
            
            labelMensaje.setText("No se a encontrado ningun deporte con ese nombre");
        }
        
        return -1;
    }
    
    private void eliminar(){
        int deporteBusqueda = buscar();
        if(deporteBusqueda>=0){
            for(int i=deporteBusqueda; i<contDeporte; i++) deportes[i] = deportes[i+1];
            
            limpiarCampos();
            labelMensaje.setText("se ha eliminado con exito");
            contDeporte--;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tFieldNombre = new javax.swing.JTextField();
        tFieldNumJugadores = new javax.swing.JTextField();
        tFieldPopularidad = new javax.swing.JTextField();
        tFieldGanarPuntos = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Deporte");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Numero de jugadores: ");

        jLabel4.setText("popularidad:");

        jLabel5.setText("Accion para ganar puntos:");

        tFieldNombre.setText("jTextField1");
        tFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldNombreActionPerformed(evt);
            }
        });
        tFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFieldNombreKeyTyped(evt);
            }
        });

        tFieldNumJugadores.setText("jTextField2");
        tFieldNumJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldNumJugadoresActionPerformed(evt);
            }
        });
        tFieldNumJugadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFieldNumJugadoresKeyTyped(evt);
            }
        });

        tFieldPopularidad.setText("jTextField3");
        tFieldPopularidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFieldPopularidadKeyTyped(evt);
            }
        });

        tFieldGanarPuntos.setText("jTextField4");
        tFieldGanarPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFieldGanarPuntosActionPerformed(evt);
            }
        });
        tFieldGanarPuntos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFieldGanarPuntosKeyTyped(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        labelMensaje.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelMensaje.setText("jLabel6");

        jLabel6.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAgregar)
                        .addGap(87, 87, 87)
                        .addComponent(btnBuscar)
                        .addGap(82, 82, 82)
                        .addComponent(btnLimpiar)
                        .addGap(44, 44, 44)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tFieldNombre)
                                    .addComponent(tFieldNumJugadores)
                                    .addComponent(tFieldGanarPuntos)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tFieldPopularidad, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)))))
                        .addGap(0, 180, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tFieldNumJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tFieldPopularidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tFieldGanarPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(labelMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFieldNombreActionPerformed

    private void tFieldNumJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldNumJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFieldNumJugadoresActionPerformed

    private void tFieldNumJugadoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFieldNumJugadoresKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isAlphabetic(caracter)) evt.consume();
    }//GEN-LAST:event_tFieldNumJugadoresKeyTyped

    private void tFieldPopularidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFieldPopularidadKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if(Character.isAlphabetic(caracter)) evt.consume();
    }//GEN-LAST:event_tFieldPopularidadKeyTyped

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFieldNombreKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        if(Character.isDigit(caracter)) evt.consume();
    }//GEN-LAST:event_tFieldNombreKeyTyped

    private void tFieldGanarPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFieldGanarPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFieldGanarPuntosActionPerformed

    private void tFieldGanarPuntosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFieldGanarPuntosKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        
        if(Character.isDigit(caracter)) evt.consume();
    }//GEN-LAST:event_tFieldGanarPuntosKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JTextField tFieldGanarPuntos;
    private javax.swing.JTextField tFieldNombre;
    private javax.swing.JTextField tFieldNumJugadores;
    private javax.swing.JTextField tFieldPopularidad;
    // End of variables declaration//GEN-END:variables
}
